Bump zlib-ng (to fix gcc10 build)
[1] is required for gcc10 build, due to incorrect `static_ltree` declaration:

    ld.lld: error: duplicate symbol: static_ltree
    >>> defined at trees.h:6 (../contrib/zlib-ng/trees.h:6)
    >>>            trees.c.o:(static_ltree) in archive contrib/zlib-ng/libzlib.a
    >>> defined at deflate_quick.c:168 (../contrib/zlib-ng/arch/x86/deflate_quick.c:168)
    >>>            deflate_quick.c.o:(.rodata+0x0) in archive contrib/zlib-ng/libzlib.a
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

  [1]: https://github.com/ClickHouse-Extras/zlib-ng/pull/2