Do not specify host port while exposing ports from container
This is fragile, since the ports on the "host" may overlaps, even with
this get_free_port() helper, which from one point make things slightly
better, but from another it is still racy. So it is better to use
ephemeral host port. And this should work since while connecting tests
uses IP address of container anyway.

Here is an example of one such failure [1]:

    ERROR: for kerberized_kafka1  Cannot start service kerberized_kafka1: driver failed programming external connectivity on endpoint rootteststoragekerberizedkafka_kerberized_kafka1_1 (e977760b45b1c7655d95583075c7b0d07271ce8434202ba5619b7aa84e23629a): Bind for 0.0.0.0:32769 failed: port is already allocated

  [1]: https://s3.amazonaws.com/clickhouse-test-reports/53085/aadd675ed777b39db6e7e578b980d66b47b1a62b/integration_tests__release__[1_4].html

Signed-off-by: Azat Khuzhin <a.khuzhin@semrush.com>