Remove unused parameter from InterruptListener.h
This should fix the compile error:
```
ClickHouse/dbms/src/Server/InterruptListener.h:20:86: error: unused parameter 'timeout' [-Werror,-Wunused-parameter]
static int sigtimedwait(const sigset_t *set, siginfo_t *info, const struct timespec *timeout) {
                                                                                     ^
1 error generated.

```