cctools: fix cctools-port compilation (update to 1010.6-ld64-951.9)
Previous error:

    52.07 In file included from macho_dylib_file.cpp:46:
    52.07 In file included from ./../code-sign-blobs/superblob.h:7:
    52.07 ./../code-sign-blobs/blob.h:185:60: error: no member named 'clone' in 'Security::BlobCore'
    52.07   185 |         { assert(validateBlob()); return specific(this->BlobCore::clone());     }