Fix config merging for from_env with replace overrides
Without this patch new test fails with:

    Exception: Failed to preprocess config '/etc/clickhouse-server/config.xml': Exception: Element <max_thread_pool_size> has value and does not have 'replace' attribute, can't process from_env substitution. Stack trace:

Signed-off-by: Azat Khuzhin <a.khuzhin@semrush.com>