Fix alignment for aligned_alloc() to fix build for glibc2.35+
In glibc2.35+ alloc_align added for aligned_alloc() alignment argument
8a9a59311551e833ca064de44ac23b193e1b704d ("Add alloc_align attribute to
memalign et al"), and this will cause an error:

    /src/ch/clickhouse/src/Common/malloc.cpp:41:26: error: requested alignment is not a power of 2 [-Werror,-Wnon-power-of-two-alignment]
        ignore(aligned_alloc(0, 0)); // -V575 NOLINT

Signed-off-by: Azat Khuzhin <a.khuzhin@semrush.com>