Fix missing cluster startup for test_quorum_inserts::test_insert_quorum_with_keeper_fail
    def test_insert_quorum_with_keeper_loss_connection():
>       zero.query(
            "DROP TABLE IF EXISTS test_insert_quorum_with_keeper_fail ON CLUSTER cluster"
        )
    def query(
>       return self.client.query(
E       AttributeError: 'NoneType' object has no attribute 'query'

CI: https://s3.amazonaws.com/clickhouse-test-reports/71406/8b3ce129456a1f85839a48538780639e2e3c3020/integration_tests__asan__old_analyzer__[6_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel3_0.log
Signed-off-by: Azat Khuzhin <a.khuzhin@semrush.com>