Mark functions as pure virtual to fix missing vtable pointer error
```
Undefined symbols for architecture x86_64:
  "vtable for DB::IModel", referenced from:
      DB::IModel::IModel() in Obfuscator.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```