ci: fix restoring metadata files for clickhouse-local in case of remote database disk
Trace:

      File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/jobs/scripts/clickhouse_proc.py", line 1089, in restore_system_metadata_files_from_remote_database_disk
        if self.system_db_uuid is None:
    AttributeError: 'ClickHouseProc' object has no attribute 'system_db_uuid'