Revert "rust: remove Cargo.toml.orig"
We cannot do this:

    [9287/14846] cd /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/rust/workspace/skim && /usr/bin/cmake -E env "CFLAGS= --gcc-toolchain=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -UNDEBUG -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -fPIC -w -ffunction-sections -fdata-sections -g -Og -g  --sysroot /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc" "CXXFLAGS= --gcc-toolchain=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -UNDEBUG -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fPIC -w -ffunction-sections -fdata-sections -g -Og -g  -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -isystem /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/llvm-project/libcxx/include -nostdinc++ --sysroot /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc" "RUSTFLAGS=-C target_feature=+ssse3 -C target_feature=+sse4.1 -C target_feature=+sse4.2 -C target_feature=+pclmulqdq -C target_feature=+popcnt -C link-arg=--sysroot -C link-arg=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -C link-arg=--gcc-toolchain=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -Adead_code -Amismatched_lifetime_syntaxes" "RUSTDOCFLAGS=-C target_feature=+ssse3 -C target_feature=+sse4.1 -C target_feature=+sse4.2 -C target_feature=+pclmulqdq -C target_feature=+popcnt -C link-arg=--sysroot -C link-arg=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -C link-arg=--gcc-toolchain=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -Adead_code -Amismatched_lifetime_syntaxes" CXXSTDLIB=cxx CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/clang-19 CC_x86_64_unknown_linux_gnu=/usr/bin/clang-19 CXX_x86_64_unknown_linux_gnu=/usr/bin/clang++-19 AR_x86_64_unknown_linux_gnu=/usr/bin/llvm-ar-19 CORROSION_BUILD_DIR=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/build/rust/workspace CARGO_BUILD_RUSTC=/rust/rustup/toolchains/nightly-2025-07-07-x86_64-unknown-linux-gnu/bin/rustc /rust/rustup/toolchains/nightly-2025-07-07-x86_64-unknown-linux-gnu/bin/cargo rustc --lib --target=x86_64-unknown-linux-gnu --no-default-features --package _ch_rust_skim_rust --crate-type=staticlib --manifest-path /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/rust/workspace/skim/Cargo.toml --target-dir /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/build/./cargo/build/workspace_5e40b --config=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/build/contrib/corrosion-cmake/config.toml --offline --locked -- -Cdefault-linker-libraries=no
    error: failed to calculate checksum of: /home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/contrib/corrosion-cmake/../rust_vendor/cxx-build-1.0.160/Cargo.toml.orig

This reverts commit 49d7324abd2c6594be87684a02588bc9a216a74b.